### ISSUE TITLE
Python3.5 support

### ISSUE THREAD

**Issue by gongbi** [conda-forge/happybase-feedstock#2]
@pmlandwehr would you help add win-64 python3.5 support?

```
C:\Users\xxx>conda install -c conda-forge happybase
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - happybase
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by pmlandwehr** [comment]
This is actually an upstream issue - happybase itself doesn't support python 3 yet, but this should be coming soon. (See [their to-do list](https://github.com/wbolster/happybase/blob/master/TODO.rst) for reference.)

**Comment by gongbi** [comment]
@pmlandwehr noted with great thanks.
